name: Check or publish

on:
  push:
    branches:
      - main
      - release
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  check-or-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2
      - run: deno fmt --check
      - run: deno lint
      - run: deno check src
      - run: deno test --allow-all

      - if: ${{ github.ref_name == 'main' && github.event_name == 'push' }}
        run: deno publish --dry-run

      - if: ${{ github.ref_name == 'release' && github.event_name == 'push' }}
        run: deno publish
